hmcts/chart-library

- ci-values.yaml
- library/Chart.yaml
- library/templates/_container.tpl
- tests/deployment-template.yaml
> make application ports optional

- .github/workflows/release-drafter.yml
- library/Chart.yaml
- library/templates/_annotations.tpl
- library/values.yaml
- tests/deployment-template.yaml
- tests/test-deployment.sh
> make prometheus optional

- .github/workflows/release-drafter.yml
- library/values.yaml
> Remove values

- ci-values.yaml
- library/templates/_container.tpl
- tests/deployment-template.yaml
> fix indentation for secrets

- library/templates/_deployment.tpl
- library/templates/_podtemplate.tpl
Splitting pod template out of deployment to reuse in job spec.
```
[ ] Yes
[x] No
```
> Split pod template

- library/templates/_container.tpl
- tests/deployment-template.yaml
> quote resources

- azure-pipelines.yaml
- ci-values.yaml
- library/templates/_configmap.tpl
- library/templates/_container.tpl
- library/templates/_dnsconfig.tpl
- library/templates/_ingress.tpl
- library/templates/_pdb.tpl
- library/templates/_service.tpl
- library/templates/tests/_test-service.tpl
- tests/configmap.yaml
- tests/deployment-template.yaml
- tests/ingress.yaml
- tests/pdb.yaml
- tests/service.yaml
- tests/test-deployment.sh
> Adding svc, configmap, ingress, pdb templates

- ci-values.yaml
- library/templates/_deployment-tests.tpl
- library/templates/_deployment_test_helpers.tpl
- tests/deployment-template.yaml
- tests/deployment-tests.yaml
- tests/test-deployment.sh
> Move deployment tests

- library/templates/_ingress.tpl
- tests/results/template-ingress.yaml
> Add path based templates

- library/templates/_service.tpl
> fixing npe

- README.md
- azure-pipelines.yaml
- tests/test-templates.sh
> Add instructions for development

- library/templates/_releasename.tpl
> Fix releaseNameOverride

- README.md
> Add documentation for templates

- README.md
- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v1/_container.tpl
- library/templates/v2/_container.tpl
- tests/results/deployment.yaml
> Add option to set all env vars from a secret

- README.md
- library/Chart.yaml
> Add read me for secret alias

- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_labels.tpl
- tests/results/configmap.yaml
- tests/results/deployment.yaml
- tests/results/hpa.yaml
- tests/results/ingress.yaml
- tests/results/pdb.yaml
- tests/results/sa.yaml
- tests/results/service.yaml
- tests/test-templates.sh
> Add support for custom labels

- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_labels.tpl
- tests/results/configmap.yaml
- tests/results/deployment.yaml
- tests/results/hpa.yaml
- tests/results/ingress.yaml
- tests/results/pdb.yaml
- tests/results/sa.yaml
- tests/results/service.yaml
- tests/test-templates.sh
Reverts hmcts/chart-library#31
> Revert "Add support for custom labels"

- library/templates/v2/_labels.tpl
> deprecate custom labels from metadata

- library/templates/v2/_container.tpl
- tests/results/deployment.yaml
> Adding restartpolicy to support job

- library/templates/v2/_container.tpl
- library/templates/v2/_podtemplate.tpl
- tests/results/deployment.yaml
> fix restart policy level

- library/templates/v2/_container.tpl
> make appsinsightskey optional

- README.md
- ci-values.yaml
- library/templates/v2/_annotations.tpl
- library/templates/v2/_configmap.tpl
- library/templates/v2/_container.tpl
- library/templates/v2/_deployment-tests.tpl
- library/templates/v2/_deployment.tpl
- library/templates/v2/_dnsconfig.tpl
- library/templates/v2/_hpa.tpl
- library/templates/v2/_ingress.tpl
- library/templates/v2/_labels.tpl
- library/templates/v2/_pdb.tpl
- library/templates/v2/_podantiaffinity.tpl
- library/templates/v2/_podtemplate.tpl
- library/templates/v2/_releasename.tpl
- library/templates/v2/_sa.tpl
- library/templates/v2/_secretcsivolumes.tpl
- library/templates/v2/_secretproviderclass.tpl
- library/templates/v2/_secrets_env.tpl
- library/templates/v2/_service.tpl
- tests/test-templates.sh
Currently we set it to None when we don't use it, i thought it would be good to avoid it.
```
[ ] Yes
[x] No
```
> Make Language property optional

- README.md
- library/templates/v2/_secretcsivolumes.tpl
- library/templates/v2/_secretproviderclass.tpl
**Does this PR introduce a breaking change?**
```
[ ] Yes
[ ] No
```
> Add condition to filter out keyvaults

- README.md
> DTSPO-2939-example to add Azure KV secrets using aliases

- README.md
> DTSPO-2939- updated readme - adding new templates

- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_ingress.tpl
- tests/results/ingress.yaml
- tests/test-templates.sh
Adding settings to enable traefik TLS with flag
> DTSPO-2879 - Traefik TLS

- README.md
- azure-pipelines.yaml
- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_container.tpl
- tests/results/deployment.yaml
https://tools.hmcts.net/jira/browse/DTSPO-2201
Added startup probes to library
```
[ ] Yes
[x ] No
```
> DTSPO-2201 Add Startup Probes

- library/templates/v2/_ingress.tpl
- tests/results/ingress.yaml
https://tools.hmcts.net/jira/browse/DTSPO-6533
```
[ ] Yes
[x] No
```
> DTSPO-6533 ingressClassName disabled by default

- README.md
> Remove unneeded note on V1 in ReadMe

- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_ingress.tpl
Add flag for enabling oauth annotations on ingress﻿
> DTSPO-6480 - Oauth annotations

- library/templates/v2/_service.tpl
ref https://github.com/helm/helm/issues/10149
> Don't chomp whitespace after document separator

- library/templates/v2/_service.tpl
So Camunda can use the latest chart version
```
[ ] Yes
[x] No
```
> Re-add annotations for traefik v1

- library/templates/v2/_service.tpl
https://tools.hmcts.net/jira/browse/DTSPO-9305
removed v1 traefik annotations
```
[ ] Yes
[x] No
```
> removed traefik v1 annotations

- README.md
- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_ingress.tpl
- tests/results/ingress.yaml
VIH-9521 - Add support for multiple ingress hosts
VIH-9521 - Add support for multiple ingress hosts
```
[ ] Yes
[x] No
```
> VIH-9521 - Add support for multiple ingress hosts

- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_ingress.tpl
- tests/results/ingress.yaml
VIH-9521 - Add Support for root Values
VIH-9521 - Add Support for root Values
```
[ ] Yes
[ x ] No
```
> VIH-9521 - Use `tpl` on `additionalIngressHosts`

- library/templates/v2/_hpa.tpl
- tests/results/hpa.yaml
> DTSPO-12023  update API

- README.md
- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_hpa.tpl
- tests/results/hpa.yaml
- tests/test-templates.sh
> Dtspo-12023 update hpa with metrics

- library/templates/v2/_hpa.tpl
- tests/test-templates.sh
> bug fix latest chart 

- library/templates/v2/_hpa.tpl
- tests/v2/hpa.yaml
> update hpa template 

- tests/test-templates.sh
Test is ignoring whitespaces( distorted indentation)
```
[ ] Yes
[ ] No
```
> Bug fix: update test script

- README.md
- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_hpa.tpl
- tests/v2/hpa.yaml
> Make Autoscaling optional based on memory / cpu

- README.md
- library/templates/v2/_hpa.tpl
> Disable HPA in dev mode

- library/templates/v2/_podtemplate.tpl
> add option to run as root

- library/templates/v2/_podtemplate.tpl
> Fix typo causing indentation issues

- library/templates/v2/_deployment_test_helpers.tpl
- library/templates/v2/_labels.tpl
> Merge Workload Identity Changes for testing

- ci-values-lang.yaml
- ci-values.yaml
- library/templates/NOTES.txt
- library/templates/v2/_secretproviderclass.tpl
- library/tests/snapshot-tests/__snapshot__/deployment_test.yaml.snap
> Lookup client id from service account to help migration

- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_podtemplate.tpl
- library/templates/v2/_tolerations.tpl
- library/tests/snapshot-tests/__snapshot__/deployment_test.yaml.snap
[DTSPO-15287](https://tools.hmcts.net/jira/browse/DTSPO-15287)
adding nodeSelector and Tolerations to pod template so it can be use in chart-jobs for cronjob.yaml
> DTSPO-15287 adding tolerations to pod template

- library/templates/v2/_container.tpl
- library/tests/snapshot-tests/__snapshot__/deployment_test.yaml.snap
[DTSPO-15293](https://tools.hmcts.net/jira/browse/DTSPO-15293)
> DTSPO-15293 fixing configMapRef

- README.md
- azure-pipelines.yaml
- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_affinity.tpl
- library/templates/v2/_podtemplate.tpl
- library/templates/v2/_tolerations.tpl
- library/templates/v2/_topologySpreadConstraints.tpl
- library/tests/snapshot-tests/__snapshot__/deployment_test.yaml.snap
> DTSPO-16054 Tweaks to affinity

- library/templates/v2/_deployment.tpl
- library/templates/v2/_podtemplate.tpl
- library/templates/v2/deployment.yaml
- tests/v2/deployment.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16054
Just in case I'm going to bump all these versions so we don't get clashes further down the line when people mix versions together
> DTSPO-16054 Bumping some helper versions to be safe

- README.md
- library/templates/v2/_hpa.tpl
- library/templates/v2/hpa.yaml
- tests/v2/hpa.yaml
https://tools.hmcts.net/jira/browse/DTSPO-16337
Add min/max replica with defaults using replicas variable, update hpa template version and references
> Add min/max replica with defaults using replicas variable, update hpa template version and references

- ci-values-lang.yaml
- ci-values.yaml
- library/templates/v2/_deployment.tpl
- library/templates/v2/_podtemplate.tpl
- library/tests/snapshot-tests/__snapshot__/deployment_test.yaml.snap
https://tools.hmcts.net/jira/browse/DTSPO-17826
Adding new customServiceAccountName input to podTemplate, updating version of podTemplate and adding new inputs to values.yaml. Tests updated to suit
> Adding new customServiceAccountName input to podTemplate
